services:
  mongo:
    image: mongo
    container_name: mongo_user_service
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ../auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    env_file:
      - ../auth-service/.env
    depends_on:
      - mongo

  user-service:
    build: .
    container_name: user-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo
      - auth-service
    volumes:
      - ./logs:/app/logs

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  mongo-data:
  grafana-data:
